### ISSUE TITLE
bench: speed up graphing over long time periods

### ISSUE THREAD

**Issue by scruzin** [ausocean/cloud#263]
Search periods greater than a week long take excessively long to graph. We should discard more data (i.e., sample less) over long periods in order to speed up graphing.

**Comment by ao-david** [comment]
There are 2 parts to this load time:
- data fetching period
- rendering period

Considering the data fetch period, there is already the concept of lower resolution, however, the backend code still gets all of the data, and only returns some of it, so this is basically the same between a resolution of 1pt per hour, and 60pts per hour. To improve the data fetch time, we could pipeline all of the requests, rather than send them serially, this would likely be more performant since golang is very multithreaded and so this could handle multiple requests quicker than it could handling 1 at a time.

In terms of the rendering period, it does take a long time to render a month of data at 60pts/hr, but decreasing the resolution to 1/hr keeps enough of the detail, but makes the render basically instant. Its also possible that there is a new version of the graphing package that we could use that would make this faster if we decided it was necessary.
