### ISSUE TITLE
Bench: Provide Embed link

### ISSUE THREAD

**Issue by ao-david** [ausocean/cloud#400]
Currently we offer short links to streams via the ```/live``` URL we could also offer an embed link so that people can embed the stream in websites (ie schools)

**Comment by trekhopton** [comment]
To quote my comment on the PR, 

> I just tested this locally and the link won't load unless embedding is enabled for the video. To do this in YouTube studio, go Details>Showmore>License>Allow Embedding.

But I'm slightly confused because the embedded video shows up on CloudBlue's broadcast page. The docs seems to indicate that it's actually true by default. But then I don't know why it didn't work when I tested the link redirect locally and the tickbox for Wagonga Inlet "Allow Embedding" was not ticked in YouTube studio, then when I ticked it, it loaded.

The following is from the docs: (https://developers.google.com/youtube/v3/live/docs/liveBroadcasts)

> contentDetails.enableEmbed	boolean
This setting indicates whether the broadcast video can be played in an embedded player. If you choose to archive the video (using the enableArchive property), this setting will also apply to the archived video.

> When you [update a broadcast](https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/update), this property must be set if your API request includes the contentDetails part in the part parameter value. However, when you [insert a broadcast](https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/insert), the property is optional and has a default value of true.

> Note: This property cannot be updated once the broadcast is in the testing or live state.
